/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carlosrivera_lab.pkg8;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Usuario Dell
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_creacion = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_nombreL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_alturaL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_edadL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_saludL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_poderL = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_aleta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_branquias = new javax.swing.JTextField();
        bt_agregar_lamias = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_alturaH = new javax.swing.JTextField();
        tf_edadH = new javax.swing.JTextField();
        tf_nombreH = new javax.swing.JTextField();
        tf_saludH = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_poderH = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_salarbolH = new javax.swing.JTextField();
        bt_agregar_hamadriades = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        tf_nombreS = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tf_edadS = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf_alturaS = new javax.swing.JTextField();
        bt_agregar_silfides = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        tf_saludS = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tf_poderS = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tf_alasS = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_modHadas = new javax.swing.JList();
        cb_hadas = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        tf_nombre1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        tf_altura1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        tf_edad1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        tf_aleta1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        tf_branquias1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        tf_alas1 = new javax.swing.JTextField();
        bt_modificar_hadas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_elimHadas = new javax.swing.JList();
        cb_elimhadas = new javax.swing.JComboBox();
        bt_eliminar_hadas = new javax.swing.JButton();
        menu_popup = new javax.swing.JPopupMenu();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jm_abrir = new javax.swing.JMenuItem();
        jm_guardar = new javax.swing.JMenuItem();
        jm_guardar_como = new javax.swing.JMenuItem();
        jm_salir = new javax.swing.JMenuItem();
        jm_about = new javax.swing.JMenuItem();

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));

        jLabel3.setText("Nombre");

        jLabel4.setText("Altura");

        jLabel6.setText("Edad");

        jLabel7.setText("Salud");

        tf_saludL.setEditable(false);
        tf_saludL.setText("475");

        jLabel8.setText("Poder");

        tf_poderL.setEditable(false);
        tf_poderL.setText("57");

        jLabel9.setText("Aleta");

        jLabel10.setText("Branquias");

        bt_agregar_lamias.setText("AGREGAR");
        bt_agregar_lamias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregar_lamiasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(tf_saludL, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_poderL, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nombreL, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_edadL, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_aleta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_alturaL, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_branquias, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(bt_agregar_lamias, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_nombreL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tf_alturaL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_edadL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_poderL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tf_saludL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_aleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tf_branquias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_agregar_lamias, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Lamias", jPanel4);

        jLabel11.setText("Nombre");

        jLabel12.setText("Edad");

        jLabel13.setText("Altura");

        tf_saludH.setEditable(false);
        tf_saludH.setText("373");

        jLabel15.setText("Salud");

        jLabel16.setText("Poder");

        tf_poderH.setEditable(false);
        tf_poderH.setText("78");

        jLabel17.setText("Salud Arbol");

        tf_salarbolH.setEditable(false);
        tf_salarbolH.setText("173");

        bt_agregar_hamadriades.setText("AGREGAR");
        bt_agregar_hamadriades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregar_hamadriadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(tf_saludH, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_poderH, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_nombreH, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_edadH, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_alturaH, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_salarbolH, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(bt_agregar_hamadriades, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_nombreH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tf_alturaH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_edadH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_poderH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tf_saludH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_salarbolH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(bt_agregar_hamadriades, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Hamadriades", jPanel5);

        jLabel18.setText("Nombre");

        jLabel19.setText("Edad");

        jLabel20.setText("Altura");

        bt_agregar_silfides.setText("AGREGAR");
        bt_agregar_silfides.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregar_silfidesActionPerformed(evt);
            }
        });

        jLabel22.setText("Salud");

        tf_saludS.setEditable(false);
        tf_saludS.setText("563");

        jLabel23.setText("Poder");

        tf_poderS.setEditable(false);
        tf_poderS.setText("67");

        jLabel24.setText("Alas");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel22)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(tf_saludS, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_poderS, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nombreS, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_edadS, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_alturaS, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tf_alasS, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_agregar_silfides, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_nombreS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(tf_alturaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_edadS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tf_poderS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(tf_saludS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(tf_alasS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(bt_agregar_silfides, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Silfides", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Salamandras", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jl_modHadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_modHadasMouseClicked(evt);
            }
        });
        jl_modHadas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jl_modHadasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jl_modHadas);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        cb_hadas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lamias", "Hamadriades", "Silfides", "Salamandras" }));
        cb_hadas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_hadasItemStateChanged(evt);
            }
        });

        jLabel32.setText("Nombre");

        jLabel33.setText("Altura");

        jLabel34.setText("Edad");

        jLabel37.setText("Aleta");

        jLabel38.setText("Branquias");

        jLabel35.setText("Alas");

        bt_modificar_hadas.setText("MODIFICAR");
        bt_modificar_hadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificar_hadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(jLabel37)
                            .addGap(18, 18, 18)
                            .addComponent(tf_aleta1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(jLabel35)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bt_modificar_hadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_alas1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLabel38)
                            .addGap(18, 18, 18)
                            .addComponent(tf_branquias1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel34)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel32)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel33)
                                .addGap(18, 18, 18)
                                .addComponent(tf_altura1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_hadas, 0, 196, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_hadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(tf_altura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(tf_aleta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(tf_branquias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_alas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_modificar_hadas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel3);

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane2.setViewportView(jl_elimHadas);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        cb_elimhadas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lamias", "Hamadriades", "Silfides", "Ssalamadras" }));

        bt_eliminar_hadas.setText("Eliminar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_eliminar_hadas, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(cb_elimhadas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(cb_elimhadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_eliminar_hadas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modificar", jPanel2);

        javax.swing.GroupLayout jd_creacionLayout = new javax.swing.GroupLayout(jd_creacion.getContentPane());
        jd_creacion.getContentPane().setLayout(jd_creacionLayout);
        jd_creacionLayout.setHorizontalGroup(
            jd_creacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_creacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jd_creacionLayout.setVerticalGroup(
            jd_creacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_creacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Hadas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simulacion");

        jMenu1.setText("Opciones");

        jm_abrir.setText("Abrir");
        jm_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_abrirActionPerformed(evt);
            }
        });
        jMenu1.add(jm_abrir);

        jm_guardar.setText("Guardar");
        jm_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_guardarActionPerformed(evt);
            }
        });
        jMenu1.add(jm_guardar);

        jm_guardar_como.setText("Guardar Como");
        jMenu1.add(jm_guardar_como);

        jm_salir.setText("Salir");
        jm_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_salirActionPerformed(evt);
            }
        });
        jMenu1.add(jm_salir);

        jm_about.setText("About");
        jm_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_aboutActionPerformed(evt);
            }
        });
        jMenu1.add(jm_about);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButton1)
                .addGap(79, 79, 79)
                .addComponent(jButton2)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.jd_creacion.setModal(true);
        this.jd_creacion.pack();
        this.jd_creacion.setLocationRelativeTo(this);
        this.jd_creacion.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_agregar_lamiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregar_lamiasActionPerformed
        int salud = 475, poder = 57;
        lamia.add(new Lamias(tf_nombreL.getText(), Double.parseDouble(
                tf_alturaL.getText()), Integer.parseInt(tf_edadL.getText()),
                salud, poder, Integer.parseInt(tf_aleta.getText()),
                Integer.parseInt(tf_branquias.getText())));
        tf_nombreL.setText("");
        tf_alturaL.setText("");
        tf_edadL.setText("");
        tf_aleta.setText("");
        tf_branquias.setText("");
    }//GEN-LAST:event_bt_agregar_lamiasActionPerformed

    private void bt_agregar_hamadriadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregar_hamadriadesActionPerformed
        int salud = 373, poder = 78, salArbol = 173;
        hamadriade.add(new Hamadriades(tf_nombreH.getText(), Double.parseDouble(
                tf_alturaH.getText()), Integer.parseInt(tf_edadH.getText()),
                salud, poder, salArbol));
        tf_nombreH.setText("");
        tf_alturaH.setText("");
        tf_edadH.setText("");
    }//GEN-LAST:event_bt_agregar_hamadriadesActionPerformed

    private void bt_agregar_silfidesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregar_silfidesActionPerformed
        int salud = 563, poder = 67;
        silfide.add(new Silfides(tf_nombreS.getText(), Double.parseDouble(
                tf_alturaS.getText()), Integer.parseInt(tf_edadS.getText()),
                salud, poder, Integer.parseInt(tf_alasS.getText())));
        tf_nombreS.setText("");
        tf_alturaS.setText("");
        tf_edadS.setText("");
        tf_alasS.setText("");
    }//GEN-LAST:event_bt_agregar_silfidesActionPerformed

    private void jl_modHadasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jl_modHadasValueChanged
        if (cb_hadas.getSelectedIndex() == 0) {
            int postn = cb_hadas.getSelectedIndex();
            if (postn != -1) {
                tf_nombre1.setText(lamia.get(postn).getNombre());
                tf_altura1.setText(lamia.get(postn).getAltura() + "");
                tf_edad1.setText(lamia.get(postn).getEdad() + "");
                tf_aleta1.setText(lamia.get(postn).getAleta() + "");
                tf_branquias1.setText(lamia.get(postn).getBranquias() + "");
                tf_alas1.setText("-NULL-");
                tf_alas1.setEnabled(false);
                tf_aleta1.setEnabled(true);
                tf_branquias1.setEnabled(true);
            } else {
            }
        } else if (cb_hadas.getSelectedIndex() == 1) {
            int postn = cb_hadas.getSelectedIndex();
            if (postn != -1) {
                tf_nombre1.setText(hamadriade.get(postn).getNombre());
                tf_altura1.setText(hamadriade.get(postn).getAltura() + "");
                tf_edad1.setText(hamadriade.get(postn).getEdad() + "");
                tf_alas1.setText("-NULL-");
                tf_alas1.setEnabled(false);
                tf_aleta1.setText("-NULL-");
                tf_aleta1.setEnabled(false);
                tf_branquias1.setText("-NULL-");
                tf_branquias1.setEnabled(false);
            } else {
            }
        } else if (cb_hadas.getSelectedIndex() == 2) {
            int postn = cb_hadas.getSelectedIndex();
            if (postn != -1) {
                tf_nombre1.setText(silfide.get(postn).getNombre());
                tf_altura1.setText(silfide.get(postn).getAltura() + "");
                tf_edad1.setText(silfide.get(postn).getEdad() + "");
                tf_alas1.setText(silfide.get(postn).getAlas() + "");
                tf_alas1.setEnabled(true);
                tf_aleta1.setText("-NULL-");
                tf_aleta1.setEnabled(false);
                tf_branquias1.setText("-NULL-");
                tf_branquias1.setEnabled(false);
            } else {
            }
        } else if (cb_hadas.getSelectedIndex() == 3) {
            int postn = cb_hadas.getSelectedIndex();
            tf_nombre1.setText(salamandra.get(postn).getNombre());
            tf_altura1.setText(salamandra.get(postn).getAltura() + "");
            tf_edad1.setText(salamandra.get(postn).getEdad() + "");
            tf_alas1.setText(salamandra.get(postn).getAlas() + "");
            tf_alas1.setEnabled(true);
            tf_aleta1.setText("-NULL-");
            tf_aleta1.setEnabled(false);
            tf_branquias1.setText("-NULL-");
            tf_branquias1.setEnabled(false);
        }
    }//GEN-LAST:event_jl_modHadasValueChanged

    private void cb_hadasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_hadasItemStateChanged
        if (cb_hadas.getSelectedIndex() == 0) {
            DefaultListModel modelo = new DefaultListModel();
            for (int i = 0; i < lamia.size(); i++) {
                modelo.addElement(lamia.get(i));
            }
            jl_modHadas.setModel(modelo);
        } else if (cb_hadas.getSelectedIndex() == 1) {
            DefaultListModel modelo = new DefaultListModel();
            for (int i = 0; i < hamadriade.size(); i++) {
                modelo.addElement(hamadriade.get(i));
            }
            jl_modHadas.setModel(modelo);
        } else if (cb_hadas.getSelectedIndex() == 2) {
            DefaultListModel modelo = new DefaultListModel();
            for (int i = 0; i < silfide.size(); i++) {
                modelo.addElement(silfide.get(i));
            }
            jl_modHadas.setModel(modelo);
        } else if (cb_hadas.getSelectedIndex() == 3) {
            DefaultListModel modelo = new DefaultListModel();
            for (int i = 0; i < salamandra.size(); i++) {
                modelo.addElement(salamandra.get(i));
            }
            jl_modHadas.setModel(modelo);
        } else {
            JOptionPane.showMessageDialog(this, "NO SE PUDO");
        }
    }//GEN-LAST:event_cb_hadasItemStateChanged

    private void bt_modificar_hadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificar_hadasActionPerformed
        int postn = jl_modHadas.getSelectedIndex();
        if (cb_hadas.getSelectedIndex() == 0) {
            lamia.get(postn).setNombre(tf_nombre1.getText());
            lamia.get(postn).setAltura(Double.parseDouble(tf_altura1.getText()));
            lamia.get(postn).setEdad(Integer.parseInt(tf_edad1.getText()));
            lamia.get(postn).setAleta(Double.parseDouble(tf_aleta1.getText()));
            lamia.get(postn).setBranquias(Integer.parseInt(tf_branquias1.getText()));
            tf_nombre1.setText("");
            tf_altura1.setText("");
            tf_edad1.setText("");
            tf_alas1.setText("");
            tf_alas1.setEnabled(false);
            tf_aleta.setText("");
            tf_aleta.setEnabled(true);
            tf_branquias1.setText("");
            tf_branquias1.setEnabled(true);
        } else if (cb_hadas.getSelectedIndex() == 1) {
            hamadriade.get(postn).setNombre(tf_nombre1.getText());
            hamadriade.get(postn).setAltura(Double.parseDouble(tf_altura1.getText()));
            hamadriade.get(postn).setEdad(Integer.parseInt(tf_edad1.getText()));
            tf_nombre1.setText("");
            tf_altura1.setText("");
            tf_edad1.setText("");
            tf_alas1.setText("");
            tf_alas1.setEnabled(false);
            tf_aleta.setText("");
            tf_aleta.setEnabled(false);
            tf_branquias1.setText("");
            tf_branquias1.setEnabled(false);
        } else if (cb_hadas.getSelectedIndex() == 2) {
            silfide.get(postn).setNombre(tf_nombre1.getText());
            silfide.get(postn).setAltura(Double.parseDouble(tf_altura1.getText()));
            silfide.get(postn).setEdad(Integer.parseInt(tf_edad1.getText()));
            silfide.get(postn).setAlas(Integer.parseInt(tf_alas1.getText()));
            tf_nombre1.setText("");
            tf_altura1.setText("");
            tf_edad1.setText("");
            tf_alas1.setText("");
            tf_alas1.setEnabled(true);
            tf_aleta.setText("");
            tf_aleta.setEnabled(false);
            tf_branquias1.setText("");
            tf_branquias1.setEnabled(false);
        } else if (cb_hadas.getSelectedIndex() == 3) {
            salamandra.get(postn).setNombre(tf_nombre1.getText());
            salamandra.get(postn).setAltura(Double.parseDouble(tf_altura1.getText()));
            salamandra.get(postn).setEdad(Integer.parseInt(tf_edad1.getText()));
            salamandra.get(postn).setAlas(Integer.parseInt(tf_alas1.getText()));
            tf_nombre1.setText("");
            tf_altura1.setText("");
            tf_edad1.setText("");
            tf_alas1.setText("");
            tf_alas1.setEnabled(true);
            tf_aleta.setText("");
            tf_aleta.setEnabled(false);
            tf_branquias1.setText("");
            tf_branquias1.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Ha Fallado");
        }
    }//GEN-LAST:event_bt_modificar_hadasActionPerformed

    private void jl_modHadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_modHadasMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {

        }
    }//GEN-LAST:event_jl_modHadasMouseClicked

    private void jm_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_abrirActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int op = fc.showOpenDialog(this);
        File f = fc.getSelectedFile();
        try {
            FileInputStream enter = new FileInputStream(f);
            ObjectInputStream selc = new ObjectInputStream(enter);
            Hadas fairy;
            try {
                while ((fairy = (Hadas) selc.readObject()) != null) {
                    if (fairy instanceof Lamias) {
                        lamia.add((Lamias) fairy);
                    } else if (fairy instanceof Hamadriades) {
                        hamadriade.add((Hamadriades) fairy);
                    } else if (fairy instanceof Silfides) {
                        silfide.add((Silfides) fairy);
                    } else if (fairy instanceof Salamandras) {
                        salamandra.add((Salamandras) fairy);
                    }
                }
                Archivo = f;
            } catch (Exception ex) {
            } finally {
                selc.close();
                enter.close();
            }
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_jm_abrirActionPerformed

    private void jm_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_guardarActionPerformed
        // TODO add your handling code here:
        if (cont > 0) {
            Archivo = new File(PATH);
            FileOutputStream fw = null;
            ObjectOutputStream bw = null;
            try {
                fw = new FileOutputStream(Archivo);
                bw = new ObjectOutputStream(fw);
                for (Lamias l : lamia) {
                    bw.writeObject(l);
                }
                for (Hamadriades h : hamadriade) {
                    bw.writeObject(h);
                }
                for (Silfides s : silfide) {
                    bw.writeObject(s);
                }
                for (Salamandras ss : salamandra) {
                    bw.writeObject(ss);
                }
                bw.flush();
            } catch (Exception ex) {
            } finally {
                try {
                    bw.close();
                    fw.close();
                } catch (Exception ex) {
                }
            }
        } else {
            JFileChooser fcs = new JFileChooser();
            int zx = fcs.showSaveDialog(this);
            if (zx == JFileChooser.APPROVE_OPTION) {
                File fs = fcs.getSelectedFile();
                PATH = fs.getAbsolutePath();
                FileOutputStream fw = null;
                ObjectOutputStream bw = null;
                try {
                    fw = new FileOutputStream(fs);
                    bw = new ObjectOutputStream(fw);
                    for (Lamias l : lamia) {
                        bw.writeObject(l);
                    }
                    for (Hamadriades h : hamadriade) {
                        bw.writeObject(h);
                    }
                    for (Silfides s : silfide) {
                        bw.writeObject(s);
                    }
                    for (Salamandras ss : salamandra) {
                        bw.writeObject(ss);
                    }
                    bw.flush();
                } catch (Exception ex) {
                } finally {
                    try {
                        bw.close();
                        fw.close();
                    } catch (Exception ex) {
                    }
                }
            }
        }

    }//GEN-LAST:event_jm_guardarActionPerformed

    private void jm_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jm_salirActionPerformed

    private void jm_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_aboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Tierra de Hadas\n" + "Version 6.6.6\n"
                + "Compiled Marzo 17 2016 7:30:78\n"
                + "Author: Carlos Rivera\n"
                + "\n"
                + "Tierra de Hadas programa experimental de Programacion\n"
                + "\n"
                + "HP y Windows son marcas de algun lugar\n"
                + "No estan asociadas con Land of Fairies");
    }//GEN-LAST:event_jm_aboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agregar_hamadriades;
    private javax.swing.JButton bt_agregar_lamias;
    private javax.swing.JButton bt_agregar_silfides;
    private javax.swing.JButton bt_eliminar_hadas;
    private javax.swing.JButton bt_modificar_hadas;
    private javax.swing.JComboBox cb_elimhadas;
    private javax.swing.JComboBox cb_hadas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JDialog jd_creacion;
    private javax.swing.JList jl_elimHadas;
    private javax.swing.JList jl_modHadas;
    private javax.swing.JMenuItem jm_about;
    private javax.swing.JMenuItem jm_abrir;
    private javax.swing.JMenuItem jm_guardar;
    private javax.swing.JMenuItem jm_guardar_como;
    private javax.swing.JMenuItem jm_salir;
    private javax.swing.JPopupMenu menu_popup;
    private javax.swing.JTextField tf_alas1;
    private javax.swing.JTextField tf_alasS;
    private javax.swing.JTextField tf_aleta;
    private javax.swing.JTextField tf_aleta1;
    private javax.swing.JTextField tf_altura1;
    private javax.swing.JTextField tf_alturaH;
    private javax.swing.JTextField tf_alturaL;
    private javax.swing.JTextField tf_alturaS;
    private javax.swing.JTextField tf_branquias;
    private javax.swing.JTextField tf_branquias1;
    private javax.swing.JTextField tf_edad1;
    private javax.swing.JTextField tf_edadH;
    private javax.swing.JTextField tf_edadL;
    private javax.swing.JTextField tf_edadS;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_nombreH;
    private javax.swing.JTextField tf_nombreL;
    private javax.swing.JTextField tf_nombreS;
    private javax.swing.JTextField tf_poderH;
    private javax.swing.JTextField tf_poderL;
    private javax.swing.JTextField tf_poderS;
    private javax.swing.JTextField tf_salarbolH;
    private javax.swing.JTextField tf_saludH;
    private javax.swing.JTextField tf_saludL;
    private javax.swing.JTextField tf_saludS;
    // End of variables declaration//GEN-END:variables
    ArrayList<Lamias> lamia = new ArrayList();
    ArrayList<Hamadriades> hamadriade = new ArrayList();
    ArrayList<Salamandras> salamandra = new ArrayList();
    ArrayList<Silfides> silfide = new ArrayList();
    File Archivo;
    int cont;
    String PATH;
}
